config/routes.rb
Crud::Engine.routes.draw do

  if (Rails.version.to_f < 4.0)
    controller 'crud' do
      match '/model/*class_name/new',         :to => :new,        :via => :get,    :as => :new
      match '/model/*class_name/:id/delete',  :to => :delete,     :via => :delete, :as => :delete
      match '/model/*class_name/:id/edit',    :to => :edit,       :via => :get,    :as => :edit
      match '/model/*class_name/:id',         :to => :show,       :via => :get,    :as => :show
      match '/model/*class_name/:id',         :to => :update,     :via => :put,    :as => :update
      match '/model/*class_name/:id',         :to => :destroy,    :via => :delete, :as => :destroy
      match '/model/(*class_name)',           :to => :create,     :via => :post,   :as => :create
      match '/model/(*class_name)',           :to => :index,      :via => :get,    :as => :index
    end
  else
    controller 'crud' do
      match '/model/*class_name/new',         :action => :new,        :via => :get,    :as => :new
      match '/model/*class_name/:id/delete',  :action => :delete,     :via => :delete, :as => :delete
      match '/model/*class_name/:id/edit',    :action => :edit,       :via => :get,    :as => :edit
      match '/model/*class_name/:id',         :action => :show,       :via => :get,    :as => :show
      match '/model/*class_name/:id',         :action => :update,     :via => :put,    :as => :update
      match '/model/*class_name/:id',         :action => :destroy,    :via => :delete, :as => :destroy
      match '/model/(*class_name)',           :action => :create,     :via => :post,   :as => :create
      match '/model/(*class_name)',           :action => :index,      :via => :get,    :as => :index
    end
  end

  #get 'dashboard' => 'dashboard#index'
  root :to => "dashboard#index"
end

app/models/crud/application_record.rb
module Crud
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/crud/klass_list.rb
# Processor to create a list of models
module Crud
  class KlassList
    def initialize
      update
    end

    def update
      #return if $all_klasses
      all_model_names = []
      ::Crud.model_path.each do |path_element|
        model_files = Dir[ File.join(path_element, '**', '*.rb').to_s ]
        model_names = model_files.map { |item| item.sub(path_element,'').sub(/^\//,'').sub(/\.rb$/,'').camelize.gsub(File::SEPARATOR,'::') }
        all_model_names += model_names
      end

      klasses = create_klasses_from_model_names(all_model_names)
      #Rails.logger.debug "create_klasses_from_model_names()"
      #klasses.each {|klass| Rails.logger.debug "#{klass}"}

      $all_klasses = remove_klasses_without_table(klasses).sort_by {|r| r.name.underscore}
      Rails.logger.debug "$all_klasses"
      $all_klasses.each {|klass| Rails.logger.debug "#{klass} (#{klass.name.underscore})"}
    end

    def all
      $all_klasses
    end

    private

    def create_klasses_from_model_names(model_names)
      output = Array.new
      klass_names = model_names.select {|model_name| (model_name.constantize.is_a? Class) && !(model_name == 'ApplicationRecord')}
      klass_names.each do |klass_name|
        begin
          klass = Object.const_get(klass_name)
          output << klass if klass_name == klass.to_s
        rescue Exception => e
          Rails.logger.debug e.message
        end
      end
      output
    end

    def remove_klasses_without_table(klasses)
      klasses.select { |klass| klass.ancestors.include?(ActiveRecord::Base) && klass.connection.table_exists?(klass.table_name) }
    end
  end
end

# p.to_s if p.respond_to?(:to_s) && /^<.+>$/.match(p.to_s).nil?

app/models/crud/menus/development_menu.rb
# Development Menu
module Crud
  class Menus::DevelopmentMenu < Hash
    def initialize
      root_dir = Crud::Engine.root

      Dir.glob( File.join(root_dir, 'app', 'controllers', '**', '*_controller.rb') ).sort.each do |controller_file|
        controller_prefix = File.dirname( controller_file.gsub(/^.*controllers/, "").gsub(/^[\\\/]/, "") )
        controller_prefix = (controller_prefix.length == 1) ? '' : controller_prefix + '/'
        controller = File.basename(controller_file, ".rb")
        controller_object = controller.camelize

        model_prefix = controller_prefix.gsub(/^.*admin/,"").gsub(/^[\\\/]/, "")
        model = controller.gsub("_controller","").singularize
        model_object = model.camelize

        if File.exist?( File.join(root_dir, 'app', 'models', model_prefix, model + '.rb') )
          next if ['report'].include?(model)

          #link_text = t(model + '.object_name').to_s.humanize
          #link_text = t(model + '.object_name').to_s.humanize.pluralize
          link_text = model.to_s.humanize.pluralize
          controller_for_url = "#{controller_prefix}#{controller.gsub("_controller","")}"
          action_for_url = 'index'

          # Initialise section reference
          section = self

          controller_prefix.split(File::SEPARATOR).each do |sub_section|
            if section[sub_section].nil?
              section[sub_section] = Hash.new
              #section[sub_section]['name'] = sub_section.to_s.humanize
            end
            section = section[sub_section]
          end

          section = Hash.new if section.nil?
          section[controller] = Hash.new if section[controller].nil?
          section[controller]['name'] = link_text
          section[controller]['controller'] = controller_for_url
          section[controller]['action'] = action_for_url
        end
      end
    end

    def depth(menu = self, count = 0)
      count += 1

      menu.each do |key, value|
        break if value.class != Hash || value.has_key?('controller')

        tmp_depth = depth(value, count)
        count = tmp_depth if tmp_depth > count
      end

      count
    end

    def items
      self
    end
  end
end

app/controllers/crud/application_controller.rb
module Crud
  #class ApplicationController < ActionController::Base
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
  end
end

app/controllers/crud/crud_base_controller.rb
module Crud
  #class CrudBaseController < ActionController::Base
  #class CrudBaseController < ::Crud.parent_controller.constantize
  class CrudBaseController < ApplicationController

    helper ::Crud::CrudHelper

    # Make these methods available to views
    helper_method :is_allowed_to_view?
    helper_method :is_allowed_to_update?

    def is_allowed_to_view?
      ::Crud.is_allowed_to_view
    end

    def is_allowed_to_update?
      ::Crud.is_allowed_to_update
    end

    protected

    def back_url
      params[:back_url] || request.env['HTTP_REFERER'] || root_url
    end

    private

  end
end

app/controllers/crud/crud_controller.rb
require_dependency "crud/crud_base_controller"

module Crud
  class CrudController < CrudBaseController

    if Rails.version.to_f >= 5.1
      around_action :catch_not_found

      before_action :get_klass_data, :only => [:show, :edit, :update, :destroy, :delete]
      before_action :get_klass_info_from_params
      before_action :get_visible_attributes
    else
      around_filter :catch_not_found

      before_filter :is_allowed_to_view?, :only => [:index, :show]
      before_filter :is_allowed_to_update?, :only => [:new, :create, :edit, :update, :destroy, :delete]
      before_filter :get_klass_data, :only => [:show, :edit, :update, :destroy, :delete]
      before_filter :get_klass_info_from_params
      before_filter :get_visible_attributes
    end

    # GET
    def index
      @search_prompt = I18n.t(:search_prompt)

      page = (params[:page]) ? params[:page].to_i : 1
      per_page = (params[:per_page]) ? params[:per_page].to_i : 10

      if( params[:search] && !params[:search].empty? && params[:search] != @search_prompt)
        where_clause = ''
        @visible_attributes.each do |attribute|
          where_clause += "LOWER(#{attribute[:column_name]}) LIKE '%#{params[:search].downcase}%' OR " if attribute[:column_data_type] == :string
        end
        where_clause.sub!(/ OR $/,'')
      else
        where_clause = nil
      end

      primary_key_name = @klass_info.primary_key(@klass_info[:class])
      if primary_key_name
        @klass_data = @klass_info[:class].where(where_clause).paginate(:page => page, :per_page => per_page).order("#{primary_key_name} ASC")
      else
        @klass_data = @klass_info[:class].where(where_clause).paginate(:page => page, :per_page => per_page)
      end

      respond_to do |format|
        format.html # index.html.erb
        format.js   # index.js.erb
        format.json { render :json => @klass_data }
        format.xml  { render :xml => @klass_data }
      end
    end

    # GET
    def show
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @klass_data }
        format.xml  { render :xml => @klass_data }
      end
    end

    # GET
    def new
      @klass_data = @klass_info[:class].new

      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @klass_data }
        format.xml  { render :xml => @klass_data }
      end
    end

    # GET
    def edit
    end

    # POST
    def create
      @klass_data = @klass_info[:class].new(klass_params)

      respond_to do |format|
        if @klass_data.save
          format.html { redirect_to show_path(:class_name => @klass_info[:name], :id => @klass_data.id), :notice => "#{@klass_info[:name]} was successfully created" }
          format.json { render :json => @klass_data, :status => :created, :location => @klass_data }
          format.xml  { head :ok }
        else
          format.html { render :action => 'new' }
          format.json { render :json => @klass_data.errors, :status => :unprocessable_entity }
          format.xml  { render :xml => @klass_data.errors, :status => :unprocessable_entity }
        end
      end
    end

    # PUT
    def update
      respond_to do |format|
        if @klass_data.update_attributes(klass_params)
          format.html { redirect_to show_path(:class_name => @klass_info[:name], :id => @klass_data.id), :notice => "#{@klass_info[:name]} was successfully updated" }
          format.json { head :no_content }
          format.xml  { head :ok }
        else
          format.html { render :action => 'edit' }
          format.json { render :json => @klass_data.errors, :status => :unprocessable_entity }
          format.xml  { render :xml => @klass_data.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE
    def delete
      @klass_data.delete

      respond_to do |format|
        format.html { redirect_to index_path(:class_name => @klass_info[:name]), :notice => "#{@klass_info[:name]}[#{params[:id]}] was successfully deleted" }
        format.json { head :no_content }
        format.xml  { head :ok }
      end
    end

    # DELETE
    def destroy
      @klass_data.destroy

      respond_to do |format|
        format.html { redirect_to index_path(:class_name => @klass_info[:name]), :notice => "#{@klass_info[:name]}[#{params[:id]}] was successfully destroyed" }
        format.json { head :no_content }
        format.xml  { head :ok }
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_klass_data
      @klass_info = get_klass_info_from_params
      @klass_data = @klass_info[:class].find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def klass_params
      visible_attributes = Array.new
      get_visible_attributes.each do |attribute|
        visible_attributes << attribute[:column_name].to_sym
      end
      params.fetch(@klass_info[:name_as_sym], visible_attributes)

      # Allow all visible attributes to be written to (bypass mass-assignment protection)
      params.require(@klass_info[:name_as_sym]).permit(visible_attributes)
    end

    def get_klass_info_from_params
      if params[:class_name]
        @klass_info = ::Crud::KlassInfo.new(params[:class_name].constantize)
      else
        render :text => "Missing class identifier"
      end
    end

    def get_visible_attributes
      @visible_attributes =  @klass_info.visible_attributes(self.action_name.to_sym)
    end

    def catch_not_found
      yield
    rescue ActiveRecord::RecordNotFound
      redirect_to back_url, :flash => { :error => "#{@klass_info[:name]} record with id=[#{params[:id]}] not found" }
    end

  end
end

app/controllers/crud/dashboard_controller.rb
require_dependency "crud/crud_base_controller"

module Crud
  class DashboardController < CrudBaseController

    if Rails.version.to_f >= 5.1
      before_action :get_klass_list
    else
      before_filter :is_allowed_to_view?, :only => [:index]
      before_filter :get_klass_list
    end

    def index
    end

    private

    def get_klass_list
      @klass_list = Crud::KlassList.new() unless @klass_list
    end
  end
end

app/helpers/crud/application_helper.rb
module Crud
  module ApplicationHelper
  end
end

app/helpers/crud/crud_helper.rb
module Crud
  module CrudHelper

    def options_for_select_tag
      options_for_select(@klass_list.all.collect{|klass| [klass.to_s, index_path(:class_name => klass)]})
    end

    def edit_field_for_attribute(klass_info, row, attribute, f)
      begin
        html = []
        if ['id','created_at', 'updated_at'].include?(attribute[:column_name])
          html << '(auto)'
        elsif attribute[:association] == :belongs_to
          unless(attribute[:association_polymorphic])
            html << f.collection_select(attribute[:column_name].to_sym, attribute[:association_class].all, :id, :to_s, :include_blank => true)
          else
            associated_attribute = klass_info.associated_polymorphic_attribute(attribute)
            if associated_attribute && associated_attribute.length == 1 && row.attributes[associated_attribute[0][:column_name]]
              html << f.collection_select(attribute[:column_name].to_sym, row.attributes[associated_attribute[0][:column_name]].constantize.all, :id, :to_s, :include_blank => true)
            else
              html << f.text_field(attribute[:column_name].to_sym)
            end
          end
        else
          case attribute[:column_data_type]
          when :text
            html << f.text_area(attribute[:column_name].to_sym, :rows => 6, :cols => 80)
          when :datetime
            html << f.datetime_select(attribute[:column_name].to_sym, :include_blank => true)
          when :date
            html << f.date_select(attribute[:column_name].to_sym, :discard_year => false, :include_blank => true)
          when :time
            html << f.time_select(attribute[:column_name].to_sym, :include_seconds => true, :include_blank => true)
          when :boolean
            html << f.select(attribute[:column_name].to_sym, [['True', true], ['False', false]], :include_blank => true)
          else
            html << f.text_field(attribute[:column_name].to_sym)
          end
        end
        html.join
      rescue Exception => e
        Rails.logger.info "#{e.class}: #{e.message}#$/#{e.backtrace.join($/)}"
        "problem constructing edit field for '#{attribute[:column_name].to_s}'"
      end
    end

    def render_attribute_value(attribute, klass_data)
      # Parameters :attribute => attribute, :klass_data => row_data
      custom_fields = @klass_info.custom_fields(attribute[:column_name], controller.action_name.to_sym)
      custom_fields_contain_a_replacement = @klass_info.custom_fields_contain_a_replacement(custom_fields)

      unless custom_fields_contain_a_replacement
        attribute_value_from_row = @klass_info.attribute_value_from_row(attribute, klass_data)
        formatted_output = attribute_value_from_row[1] ? "[#{attribute_value_from_row[0]}] #{attribute_value_from_row[1]}" : "#{attribute_value_from_row[0]}"

        unless (attribute[:association] && attribute[:association] == :belongs_to)
          return formatted_output
        else
          unless attribute[:association_polymorphic]
            return link_to formatted_output, show_path(:class_name => attribute[:association_class].name, :id => attribute_value_from_row[0])
          else
            associated_polymorphic_class = @klass_info.associated_polymorphic_class(attribute, klass_data)
            if associated_polymorphic_class
              return link_to formatted_output, show_path(:class_name => associated_polymorphic_class.name, :id => attribute_value_from_row[0])
            else
              return formatted_output
            end
          end
        end
      else
        ''.html_safe
      end

    end

    def render_custom_fields(attribute, klass_data, klass_info)
      out = ''

      custom_fields = klass_info.custom_fields(attribute[:column_name], controller.action_name.to_sym)
      custom_fields.each do |field|
        out += render field[:partial], {field[:record_data_parameter].to_sym => klass_data}.merge(field[:additional_partial_parameters])
        out += '<br/>'
      end

      out.html_safe
    end

    def render_attribute_value_and_custom_fields(attribute, klass_data, klass_info)
      (render_attribute_value(attribute, klass_data) + render_custom_fields(attribute, klass_data, klass_info)).html_safe
    end

    private

    # Handler to send application URIs back to the application
    def method_missing(method, *args, &block)
      if (method.to_s.end_with?('_path') || method.to_s.end_with?('_url')) && main_app.respond_to?(method)
        main_app.send(method, *args)
      else
        super
      end
    end

  end
end

app/helpers/crud/dashboard_helper.rb
module Crud
  module DashboardHelper
  end
end

app/views/crud/crud/_attribute_value.html.erb
<% # Parameters :attribute => attribute, :klass_data => row_data %>
<%#= #render_attribute_value(attribute, klass_data) %>
<%#= #render_custom_fields(attribute, klass_data, @klass_info) %>

<%= render_attribute_value_and_custom_fields(attribute, klass_data, @klass_info) %>

app/views/crud/crud/_error_messages.html.erb
<% if model && model.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this <%= model.to_s %> from being saved:</h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%=message%></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/crud/crud/_flash_messages.html.erb
<%= stylesheet_link_tag 'crud/flash_notices', :media => 'screen' %>
<div class="clearthis">&nbsp;</div>
<% flash.each do |type, value| %>
  <% unless flash.now[type.to_sym].blank? %>
    <div id='flash-<%="#{type.to_s}"%>' class='flash_message flash_<%="#{type.to_s}"%>' >
      <p><%= "#{value}" %></p>
    </div>
    <div class="clearthis">&nbsp;</div>
  <% end %>
<% end %>

app/views/crud/crud/_form.html.erb
<%= render 'error_messages', :model => @klass_data %>
<div class="actions">
  <%= f.submit %>
</div>
<% @visible_attributes.each do |attribute| %>
  <% unless ['id','created_at', 'updated_at'].include?(attribute[:column_name]) %>
    <div class="field">
      <%= f.label attribute[:column_name].to_sym %>
      <%= '<span style="color: red;">*</span>'.html_safe if attribute[:required] -%>
      <br />
      <% custom_fields = @klass_info.custom_fields(attribute[:column_name], controller.action_name.to_sym) %>
      <% custom_fields_contain_a_replacement = @klass_info.custom_fields_contain_a_replacement(custom_fields) %>
      <% unless custom_fields_contain_a_replacement %>
        <%= edit_field_for_attribute(@klass_info, @klass_data, attribute, f).html_safe %>
      <% end %>
      <% custom_fields.each do |field| %>
        <%= render field[:partial], {field[:record_data_parameter].to_sym => @klass_data}.merge(field[:additional_partial_parameters]) %><br/>
      <% end %>
    </div>
  <% end %>
<% end %>
<div class="actions">
  <%= f.submit %>
</div>

app/views/crud/crud/_klass_data.html.erb
<div style="clear: both;"/>
<br />

<div style="clear: both;"/>
<% if is_allowed_to_update? %>
  <%= link_to "New #{@klass_info[:name]}", new_path(:class_name => @klass_info[:name]) %>
<% end %>

<div style="clear: both;"/>
<br />

<div style="clear: both;"/>
<div id="crud_pagination" class="flickr_pagination" style="text-align: left; float: left; width: 75%;">
  Items per page:
  <%= select_tag :per_page, options_for_select([5, 10, 25, 50, 100], (controller.params[:per_page] ? controller.params[:per_page].to_i : 10)) %>
  <br /><br />
  <div id="upper_pagination_overlay" class="pagination_overlay" style="height: 16px;">
    <%= will_paginate @klass_data %>
    <%= hidden_field_tag :page, (controller.params[:page] ? controller.params[:page] : 1) %>
  </div>
  <br />
  <%= page_entries_info @klass_data %>
  <br /><br />
</div>
<div id="crud_search" style="text-align: right; float: right; width: 20%; min-width: 250px;">
  <%= form_tag '#', :id => 'search_form', :method => :get do %>
    Search:
    <%= text_field_tag :search, ((controller.params[:search].nil? || controller.params[:search].empty?) ? @search_prompt : controller.params[:search]),
      :value => ((controller.params[:search].nil? || controller.params[:search].empty?) ? @search_prompt : controller.params[:search]),
      :style => ((controller.params[:search].nil? || controller.params[:search].empty?) ? 'color:#777;' : ''),
      :onfocus => "if(this.value == '#{@search_prompt}') {this.style.color=''; this.value = '';}",
      :onblur => "if(this.value == '') {this.style.color='#777'; this.value = '#{@search_prompt}';}"
    -%>
    <%= image_submit_tag 'crud/search-icon.png', { :height => '16' } %>
    <br />
    <% if false %>
      <%= check_box_tag :crud_advanced_search, nil, ((controller.params[:advanced_search]=='true') ? true : false) %> <%= I18n.t(:advanced_search_prompt) %>
    <% end %>
  <% end %>
</div>
<div style="clear: both;"/>
<br />

<% if @klass_data.count > 0 %>
  <table id="klass_table">
    <thead>
      <tr>
        <% if false %>
          <th></th>
        <% end %>
        <% @visible_attributes.each do |attribute| %>
          <th>
            <%= label(@klass_info[:name].to_sym, attribute[:column_name].to_sym) %>
            <% if false %>
              <%= "(#{attribute[:column_type]})" %>
              <%= "#{attribute[:association].to_s} #{attribute[:association_class]}" if attribute[:association] %>
            <% end %>
          </th>
        <% end %>
        <% if is_allowed_to_view? %>
          <th></th>
        <% end %>
        <% if is_allowed_to_update? %>
          <th></th>
          <th></th>
          <th></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @klass_data.each do |row| %>
        <tr style="background-color:<%= cycle("lightblue", "lightgrey") %>;">
          <% if false %>
            <td><%= check_box 'selected_items', row.attributes['id'], :id => nil %></td>
          <% end %>
          <% @visible_attributes.each do |attribute| %>
            <td>
              <%= render_attribute_value_and_custom_fields(attribute, row, @klass_info) %>
            </td>
          <% end %>
          <% if is_allowed_to_view? %>
            <td><%= link_to('Show', show_path(:class_name => @klass_info[:name], :id => row.id)) if ::Crud::KlassInfo.primary_key_is_id?(@klass_info[:class]) %></td>
          <% end %>
          <% if is_allowed_to_update? %>
            <td><%= link_to('Edit', edit_path(:class_name => @klass_info[:name], :id => row.id)) if ::Crud::KlassInfo.primary_key_is_id?(@klass_info[:class]) %></td>
            <td><%= link_to('Delete', delete_path(:class_name => @klass_info[:name], :id => row.id), :data => { :confirm => "Are you sure you want to delete '#{row}'?" }, :method => :delete) if ::Crud::KlassInfo.primary_key_is_id?(@klass_info[:class]) %></td>
            <td><%= link_to('Destroy', destroy_path(:class_name => @klass_info[:name], :id => row.id), :data => { :confirm => "Are you sure you want to destroy '#{row}'?" }, :method => :delete) if ::Crud::KlassInfo.primary_key_is_id?(@klass_info[:class]) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br />

  <div class="flickr_pagination" style="text-align: left;">
    <%= page_entries_info @klass_data %>
    <br /><br />
    <div id="lower_pagination_overlay" class="pagination_overlay" style="height: 16px;">
      <%= will_paginate @klass_data %>
    </div>
  </div>
  <div style="clear: both;"/>
  <br />
<% end # @klass_data.count > 0 %>

<% @klass_info.global_custom_fields(controller.action_name.to_sym).each do |field| %>
  <%= render field[:partial], {field[:record_data_parameter].to_sym => @klass_data}.merge(field[:additional_partial_parameters]) %><br/>
<% end %>

<div style="clear: both;"/>
<% if is_allowed_to_update? %>
  <%= link_to "New #{@klass_info[:name]}", new_path(:class_name => @klass_info[:name]) %>
<% end %>

<div style="clear: both;"/>
<br />

app/views/crud/crud/edit.html.erb
<h1><%= "Editing #{@klass_info[:name]}" %></h1>

<%= form_for(
  @klass_data,
  :as => @klass_info[:name_as_sym],
  :url => update_path(:class_name => @klass_info[:name], :id => @klass_data.id),
  :html => {:multipart => 'true'},
  :method => :put
  ) do |f| %>
  <%= render 'form', :f => f %>
<% end %>

<% if ::Crud::KlassInfo.primary_key_is_id?(@klass_info[:class]) %>
  <%= link_to 'Show', show_path(:class_name => @klass_info[:name], :id => @klass_data.id) %> |
<% end %>

<%= link_to "Back (List all #{@klass_info[:name].pluralize})", index_path(:class_name => @klass_info[:name]) %>

app/views/crud/crud/index.html.erb
<%= stylesheet_link_tag "crud/application", :media => "all" %>
<%= javascript_include_tag "crud/application" %>
<h1><%= "Listing #{@klass_info[:name].pluralize}" %></h1>
<div id="klass_data" style="min-width: 1045px;">
  <%= render('klass_data') %>
</div>

app/views/crud/crud/index.js.erb
$("#klass_data").html("<%= escape_javascript(render("klass_data")) %>");

app/views/crud/crud/new.html.erb
<h1><%= "New #{@klass_info[:name]}" %></h1>

<%= form_for(
  @klass_data,
  :as => @klass_info[:name_as_sym],
  :url => create_path(:class_name => @klass_info[:name]),
  :html => {:multipart => 'true'},
  :method => :post
  ) do |f| %>
  <%= render 'form', :f => f %>
<% end %>

<%= link_to "Back (List all #{@klass_info[:name].pluralize})", index_path(:class_name => @klass_info[:name]) %>

app/views/crud/crud/show.html.erb
<%= render 'error_messages', :model => @klass_data %>

<% if is_allowed_to_update? %>
  <%= link_to 'Edit', edit_path(:class_name => @klass_info[:name], :id => @klass_data.id) %> |
<% end %>
<%= link_to "Back (List all #{@klass_info[:name].pluralize})", index_path(:class_name => @klass_info[:name]) %>

<br/>
<br/>

<% @visible_attributes.each do |attribute| %>
  <p>
    <b><%= label(@klass_info[:name].to_sym, attribute[:column_name].to_sym) %>:</b>
    <%= render_attribute_value_and_custom_fields(attribute, @klass_data, @klass_info) %>
  </p>
<% end %>

<br/>

<% unless @klass_info[:has_one].empty? %>
  <b>Has one:</b><br/>
  <% @klass_info[:has_one].each do |association| %>
    <% association_value = @klass_data.send("#{association[:association_name]}") %>
    <%= "#{association[:association_name]}" %>
    <% if association_value && ::Crud::KlassInfo.primary_key_is_id?(association_value.class) %>
      [<%= link_to("#{association_value}", show_path(:class_name => association_value.class.name, :id => association_value.id)) %>]
    <% end %>
    <br/>
  <% end %>
<% end %>

<% unless @klass_info[:has_many].empty? %>
  <b>Has many:</b><br/>
  <% @klass_info[:has_many].each do |association| %>
    <% association_values = @klass_data.send("#{association[:association_name]}") %>
    <%= "#{association[:association_name]}" %>
    <% if association_values %>
      <% association_values.each do |association_value| %>
        <% if ::Crud::KlassInfo.primary_key_is_id?(association_value.class) %>
          [<%= link_to("#{association_value}", show_path(:class_name => association_value.class.name, :id => association_value.id)) %>]
        <% end %>
      <% end %>
    <% else %>
      <%= "(0)" %>
    <% end %>
    <br/>
  <% end %>
<% end %>

<% unless @klass_info[:has_and_belongs_to_many].empty? %>
  <b>Has and belongs to many:</b><br/>
  <% @klass_info[:has_and_belongs_to_many].each do |association| %>
    <% association_values = @klass_data.send("#{association[:association_name]}") %>
    <%= "#{association[:association_name]}" %>
    <% if association_values %>
      <% association_values.each do |association_value| %>
        <% if ::Crud::KlassInfo.primary_key_is_id?(association_value.class) %>
          [<%= link_to("#{association_value}", show_path(:class_name => association_value.class.name, :id => association_value.id)) %>]
        <% end %>
      <% end %>
    <% else %>
      <%= "(0)" %>
    <% end %>
    <br/>
  <% end %>
<% end %>

<br/>

<% @klass_info.global_custom_fields(controller.action_name.to_sym).each do |field| %>
  <%= render field[:partial], {field[:record_data_parameter].to_sym => @klass_data}.merge(field[:additional_partial_parameters]) %><br/>
<% end %>

<% if is_allowed_to_update? %>
  <%= link_to 'Edit', edit_path(:class_name => @klass_info[:name], :id => @klass_data.id) %> |
<% end %>
<%= link_to "Back (List all #{@klass_info[:name].pluralize})", index_path(:class_name => @klass_info[:name]) %>